In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dates = "C:\M52.0\mlops_pipeline\Base_de_datos1.csv"

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Dell\AppData\Local\Temp\ipykernel_19740\2304177563.py:1: SyntaxWarning: invalid escape sequence '\M'
  dates = "C:\M52.0\mlops_pipeline\Base_de_datos1.csv"

In [4]:
df = pd.read_csv(dates)

In [5]:
print(df.shape)
print(df.columns.tolist())
display(df.head())

(10763, 23)
['tipo_credito', 'fecha_prestamo', 'capital_prestado', 'plazo_meses', 'edad_cliente', 'tipo_laboral', 'salario_cliente', 'total_otros_prestamos', 'cuota_pactada', 'puntaje', 'puntaje_datacredito', 'cant_creditosvigentes', 'huella_consulta', 'saldo_mora', 'saldo_total', 'saldo_principal', 'saldo_mora_codeudor', 'creditos_sectorFinanciero', 'creditos_sectorCooperativo', 'creditos_sectorReal', 'promedio_ingresos_datacredito', 'tendencia_ingresos', 'Pago_atiempo']

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,12/21/24 11:31,3692160,10,42,Independiente,8000000,2500000,341296,"88,768094",...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,4/22/25 9:47,840000,6,60,Empleado,3000000,2000000,124876,"95,227787",...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,1/8/26 12:22,5974028,10,36,Independiente,4036000,829000,529554,"47,613894",...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,8/4/25 12:04,1671240,6,48,Empleado,1524547,498000,252420,"95,227787",...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,4/26/25 11:24,2781636,11,44,Empleado,5000000,4000000,217037,"95,227787",...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

In [17]:
print(f"Dataset cargado correctamente. Registros: {df.shape[0]}, Columnas: {df.shape[1]}")
df.head()

Dataset cargado correctamente. Registros: 10763, Columnas: 23

,tipo_credito,fecha_prestamo,capital_prestado,plazo_meses,edad_cliente,tipo_laboral,salario_cliente,total_otros_prestamos,cuota_pactada,puntaje,...,saldo_mora,saldo_total,saldo_principal,saldo_mora_codeudor,creditos_sectorFinanciero,creditos_sectorCooperativo,creditos_sectorReal,promedio_ingresos_datacredito,tendencia_ingresos,Pago_atiempo
0,7,12/21/24 11:31,3692160,10,42,Independiente,8000000,2500000,341296,"88,768094",...,0.0,51258.0,51258.0,0.0,5,0,0,908526.0,Estable,1
1,4,4/22/25 9:47,840000,6,60,Empleado,3000000,2000000,124876,"95,227787",...,0.0,8673.0,8673.0,0.0,0,0,2,939017.0,Creciente,1
2,9,1/8/26 12:22,5974028,10,36,Independiente,4036000,829000,529554,"47,613894",...,0.0,18702.0,18702.0,0.0,3,0,0,NaN,NaN,0
3,4,8/4/25 12:04,1671240,6,48,Empleado,1524547,498000,252420,"95,227787",...,0.0,15782.0,15782.0,0.0,3,0,0,1536193.0,Creciente,1
4,9,4/26/25 11:24,2781636,11,44,Empleado,5000000,4000000,217037,"95,227787",...,0.0,204804.0,204804.0,0.0,3,0,1,933473.0,Creciente,1

In [6]:
print("TAMAÑO DEL DATASET")
print(df.shape)

TAMAÑO DEL DATASET
(10763, 23)

In [7]:
print("\nTIPOS DE DATOS")
print(df.dtypes)

TIPOS DE DATOS
tipo_credito                       int64
fecha_prestamo                       str
capital_prestado                   int64
plazo_meses                        int64
edad_cliente                       int64
tipo_laboral                         str
salario_cliente                    int64
total_otros_prestamos              int64
cuota_pactada                      int64
puntaje                              str
puntaje_datacredito              float64
cant_creditosvigentes              int64
huella_consulta                    int64
saldo_mora                       float64
saldo_total                      float64
saldo_principal                  float64
saldo_mora_codeudor              float64
creditos_sectorFinanciero          int64
creditos_sectorCooperativo         int64
creditos_sectorReal                int64
promedio_ingresos_datacredito    float64
tendencia_ingresos                   str
Pago_atiempo                       int64
dtype: object

In [8]:
print("\nVALORES NULOS")
print(df.isnull().sum())

VALORES NULOS
tipo_credito                        0
fecha_prestamo                      0
capital_prestado                    0
plazo_meses                         0
edad_cliente                        0
tipo_laboral                        0
salario_cliente                     0
total_otros_prestamos               0
cuota_pactada                       0
puntaje                             0
puntaje_datacredito                 6
cant_creditosvigentes               0
huella_consulta                     0
saldo_mora                        156
saldo_total                       156
saldo_principal                   405
saldo_mora_codeudor               590
creditos_sectorFinanciero           0
creditos_sectorCooperativo          0
creditos_sectorReal                 0
promedio_ingresos_datacredito    2930
tendencia_ingresos               2932
Pago_atiempo                        0
dtype: int64

In [9]:
print("\nDISTRIBUCIÓN DEL TARGET")
print(df["Pago_atiempo"].value_counts())

DISTRIBUCIÓN DEL TARGET
Pago_atiempo
1    10252
0      511
Name: count, dtype: int64

In [10]:
print("\nPORCENTAJES DEL TARGET")
print(df["Pago_atiempo"].value_counts(normalize=True) * 100)

PORCENTAJES DEL TARGET
Pago_atiempo
1    95.252253
0     4.747747
Name: proportion, dtype: float64

In [19]:
print("VALORES DE puntaje:")
print(df["puntaje"].unique())

print("\nVALORES DE tendencia_ingresos:")
print(df["tendencia_ingresos"].unique())

VALORES DE puntaje:
<StringArray>
[ '88,768094',  '95,227787',  '47,613894',  '49,161959',  '46,387527',
  '-4,158836',  '40,818275', '-11,093652',    '89,2295',  '58,597591',
 ...
  '61,221842',   '3,486288',  '53,342788',   '61,72483',  '50,543588',
  '42,181932',  '-5,881654',  '22,632236',  '-2,469724',  '13,134355']
Length: 248, dtype: str

VALORES DE tendencia_ingresos:
<StringArray>
[    'Estable',   'Creciente',           nan, 'Decreciente',        '8315',
           '0',      '158042',        '3978',        '9147',      '168750',
      '-28589',     '1000000',     '-566272',       '24702',       '31837',
      '122727',      '417087',        '9090',      '173031',      '-70715',
     '-435177',     '-702927',       '-4105',       '54683',       '22832',
      '209090',        '5697',       '10808',        '-288',     '-164315',
     '2029000',       '17181',       '15245',       '82657',       '52862',
     '1817052',       '75761',      '146918',     '1123000',       '15090',
     '4250635',       '22363',     '-101368',       '86286',       '65988',
       '77975',     '-224714']
Length: 47, dtype: str